// Code generated by go-bindata.
// sources:
// public/css/ilcorsaronero/style.css
// public/img/arenavision/logo_av2015.png
// public/img/dilbert/dilbert-logo.png
// public/img/dilbert/dilbert_character_top.png
// public/img/ilcorsaronero/h_logo.gif
// public/js/ilcorsaronero/torrent-add.js
// public/tmpl/arenavision/schedule.tmpl
// public/tmpl/ilcorsaronero/_base.tmpl
// public/tmpl/ilcorsaronero/_browser-sync.tmpl
// public/tmpl/ilcorsaronero/index.tmpl
// public/tmpl/ilcorsaronero/index.tmpl.old
// public/tmpl/partials/_footer.tmpl
// public/tmpl/partials/_header.tmpl
// public/tmpl/test/transmission.tmpl
// DO NOT EDIT!

package templates

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

// bindataRead reads the given file from disk. It returns an error on failure.
func bindataRead(path, name string) ([]byte, error) {
	buf, err := ioutil.ReadFile(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset %s at %s: %v", name, path, err)
	}
	return buf, err
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

// cssIlcorsaroneroStyleCss reads file data from disk. It returns an error on failure.
func cssIlcorsaroneroStyleCss() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/css/ilcorsaronero/style.css"
	name := "css/ilcorsaronero/style.css"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// imgArenavisionLogo_av2015Png reads file data from disk. It returns an error on failure.
func imgArenavisionLogo_av2015Png() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/img/arenavision/logo_av2015.png"
	name := "img/arenavision/logo_av2015.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// imgDilbertDilbertLogoPng reads file data from disk. It returns an error on failure.
func imgDilbertDilbertLogoPng() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/img/dilbert/dilbert-logo.png"
	name := "img/dilbert/dilbert-logo.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// imgDilbertDilbert_character_topPng reads file data from disk. It returns an error on failure.
func imgDilbertDilbert_character_topPng() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/img/dilbert/dilbert_character_top.png"
	name := "img/dilbert/dilbert_character_top.png"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// imgIlcorsaroneroH_logoGif reads file data from disk. It returns an error on failure.
func imgIlcorsaroneroH_logoGif() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/img/ilcorsaronero/h_logo.gif"
	name := "img/ilcorsaronero/h_logo.gif"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// jsIlcorsaroneroTorrentAddJs reads file data from disk. It returns an error on failure.
func jsIlcorsaroneroTorrentAddJs() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/js/ilcorsaronero/torrent-add.js"
	name := "js/ilcorsaronero/torrent-add.js"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplArenavisionScheduleTmpl reads file data from disk. It returns an error on failure.
func tmplArenavisionScheduleTmpl() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/tmpl/arenavision/schedule.tmpl"
	name := "tmpl/arenavision/schedule.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplIlcorsaronero_baseTmpl reads file data from disk. It returns an error on failure.
func tmplIlcorsaronero_baseTmpl() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/tmpl/ilcorsaronero/_base.tmpl"
	name := "tmpl/ilcorsaronero/_base.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplIlcorsaronero_browserSyncTmpl reads file data from disk. It returns an error on failure.
func tmplIlcorsaronero_browserSyncTmpl() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/tmpl/ilcorsaronero/_browser-sync.tmpl"
	name := "tmpl/ilcorsaronero/_browser-sync.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplIlcorsaroneroIndexTmpl reads file data from disk. It returns an error on failure.
func tmplIlcorsaroneroIndexTmpl() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/tmpl/ilcorsaronero/index.tmpl"
	name := "tmpl/ilcorsaronero/index.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplIlcorsaroneroIndexTmplOld reads file data from disk. It returns an error on failure.
func tmplIlcorsaroneroIndexTmplOld() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/tmpl/ilcorsaronero/index.tmpl.old"
	name := "tmpl/ilcorsaronero/index.tmpl.old"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplPartials_footerTmpl reads file data from disk. It returns an error on failure.
func tmplPartials_footerTmpl() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/tmpl/partials/_footer.tmpl"
	name := "tmpl/partials/_footer.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplPartials_headerTmpl reads file data from disk. It returns an error on failure.
func tmplPartials_headerTmpl() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/tmpl/partials/_header.tmpl"
	name := "tmpl/partials/_header.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// tmplTestTransmissionTmpl reads file data from disk. It returns an error on failure.
func tmplTestTransmissionTmpl() (*asset, error) {
	path := "/home/user/Code/go/src/github.com/mmbros/mananno/public/tmpl/test/transmission.tmpl"
	name := "tmpl/test/transmission.tmpl"
	bytes, err := bindataRead(path, name)
	if err != nil {
		return nil, err
	}

	fi, err := os.Stat(path)
	if err != nil {
		err = fmt.Errorf("Error reading asset info %s at %s: %v", name, path, err)
	}

	a := &asset{bytes: bytes, info: fi}
	return a, err
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"css/ilcorsaronero/style.css": cssIlcorsaroneroStyleCss,
	"img/arenavision/logo_av2015.png": imgArenavisionLogo_av2015Png,
	"img/dilbert/dilbert-logo.png": imgDilbertDilbertLogoPng,
	"img/dilbert/dilbert_character_top.png": imgDilbertDilbert_character_topPng,
	"img/ilcorsaronero/h_logo.gif": imgIlcorsaroneroH_logoGif,
	"js/ilcorsaronero/torrent-add.js": jsIlcorsaroneroTorrentAddJs,
	"tmpl/arenavision/schedule.tmpl": tmplArenavisionScheduleTmpl,
	"tmpl/ilcorsaronero/_base.tmpl": tmplIlcorsaronero_baseTmpl,
	"tmpl/ilcorsaronero/_browser-sync.tmpl": tmplIlcorsaronero_browserSyncTmpl,
	"tmpl/ilcorsaronero/index.tmpl": tmplIlcorsaroneroIndexTmpl,
	"tmpl/ilcorsaronero/index.tmpl.old": tmplIlcorsaroneroIndexTmplOld,
	"tmpl/partials/_footer.tmpl": tmplPartials_footerTmpl,
	"tmpl/partials/_header.tmpl": tmplPartials_headerTmpl,
	"tmpl/test/transmission.tmpl": tmplTestTransmissionTmpl,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"css": &bintree{nil, map[string]*bintree{
		"ilcorsaronero": &bintree{nil, map[string]*bintree{
			"style.css": &bintree{cssIlcorsaroneroStyleCss, map[string]*bintree{}},
		}},
	}},
	"img": &bintree{nil, map[string]*bintree{
		"arenavision": &bintree{nil, map[string]*bintree{
			"logo_av2015.png": &bintree{imgArenavisionLogo_av2015Png, map[string]*bintree{}},
		}},
		"dilbert": &bintree{nil, map[string]*bintree{
			"dilbert-logo.png": &bintree{imgDilbertDilbertLogoPng, map[string]*bintree{}},
			"dilbert_character_top.png": &bintree{imgDilbertDilbert_character_topPng, map[string]*bintree{}},
		}},
		"ilcorsaronero": &bintree{nil, map[string]*bintree{
			"h_logo.gif": &bintree{imgIlcorsaroneroH_logoGif, map[string]*bintree{}},
		}},
	}},
	"js": &bintree{nil, map[string]*bintree{
		"ilcorsaronero": &bintree{nil, map[string]*bintree{
			"torrent-add.js": &bintree{jsIlcorsaroneroTorrentAddJs, map[string]*bintree{}},
		}},
	}},
	"tmpl": &bintree{nil, map[string]*bintree{
		"arenavision": &bintree{nil, map[string]*bintree{
			"schedule.tmpl": &bintree{tmplArenavisionScheduleTmpl, map[string]*bintree{}},
		}},
		"ilcorsaronero": &bintree{nil, map[string]*bintree{
			"_base.tmpl": &bintree{tmplIlcorsaronero_baseTmpl, map[string]*bintree{}},
			"_browser-sync.tmpl": &bintree{tmplIlcorsaronero_browserSyncTmpl, map[string]*bintree{}},
			"index.tmpl": &bintree{tmplIlcorsaroneroIndexTmpl, map[string]*bintree{}},
			"index.tmpl.old": &bintree{tmplIlcorsaroneroIndexTmplOld, map[string]*bintree{}},
		}},
		"partials": &bintree{nil, map[string]*bintree{
			"_footer.tmpl": &bintree{tmplPartials_footerTmpl, map[string]*bintree{}},
			"_header.tmpl": &bintree{tmplPartials_headerTmpl, map[string]*bintree{}},
		}},
		"test": &bintree{nil, map[string]*bintree{
			"transmission.tmpl": &bintree{tmplTestTransmissionTmpl, map[string]*bintree{}},
		}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

