
// Generated by gentmpl; *** DO NOT EDIT ***
// Created: 2017-03-12 21:38:13
// Params: no_cache=true, no_go_format=true, asset_manager="go-bindata", func_map="funcMap"

package templates

import (
"html/template"
	"io"
	"path/filepath"
)


	// type definitions
	type (
		// templateEnum is the type of the Templates
		templateEnum uint8
		// PageEnum is the type of the Pages
		PageEnum uint8
	)
	// number of templates
	const templatesLen = 2
	// PageEnum constants
	const (
		PageArenavisionChannel PageEnum = iota
		PageArenavisionSchedule
		PageTestTransmission
		)
	




// Files returns the files used by the `t` template
func (t templateEnum) Files() []string {
	var (
		// files paths
		files = [...]string{ "partials/_header.tmpl", "partials/_footer.tmpl", "arenavision/schedule.tmpl", "test/transmission.tmpl"  }
		// template-index to array of file-index
		ti2afi = [...][]uint8{
		{ 0, 1, 2 }, // av_schedule
		{ 0, 1, 3 }, // test_transmission
		}
	)
	// get the template files indexes
	idxs := ti2afi[t]
	// build the array of files
	astr := make([]string, len(idxs))
	for j, idx := range idxs {
		astr[j] = files[idx]
	}
	return astr
}


// Files returns the files used by the template of the page
func (page PageEnum) Files() []string {
	// from page to template indexes
	var p2t = [...]templateEnum{0, 0, 1}
	// get the template of the page
	t := p2t[page]
	return t.Files()
}


	
// Template returns the template.Template of the page
func (page PageEnum) Template() *template.Template {
files := page.Files()


// use go-bindata MustAsset func to load templates
tmpl := template.New(filepath.Base(files[0])).Funcs(funcMap)
for _, path := range files {
	tmpl.Parse(string(MustAsset(path)))
}
return tmpl

}



// Base returns the template name of the page
func (page PageEnum) Base() string {
	var bases = [...]string{ "channel", "schedule", "main" }
	
		
	return bases[page]
	
}


// Execute applies a parsed page template to the specified data object,
// writing the output to wr.
// If an error occurs executing the template or writing its output, execution
// stops, but partial results may already have been written to the output writer.
// A template may be executed safely in parallel.
func (page PageEnum) Execute(wr io.Writer, data interface{}) error {
	tmpl := page.Template()
	name := page.Base()
	if name != "" {
		return tmpl.ExecuteTemplate(wr, name, data)
	}
	return tmpl.Execute(wr, data)
}


/*
func main(){
	var page = PageArenavisionChannel
	wr := os.Stdout

	if err := page.Execute(wr, nil); err != nil {
		fmt.Print(err)
	}
}
*/

